services:
  mcstatus:
    container_name: "mcstatus"
    image: mcstatus
    build:
      context: .
      dockerfile: MCStatus/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - GITHUB_USERNAME=${GITHUB_USERNAME}
    environment:
      - MCSTATUS__DISCORD__COMMANDPATH=${MCSTATUS__DISCORD__COMMANDPATH}
      - MCSTATUS__DISCORD__REGISTERCOMMANDS=${MCSTATUS__DISCORD__REGISTERCOMMANDS}
      - MCSTATUS__DISCORD__TOKEN=${MCSTATUS__DISCORD__TOKEN}
    env_file:
      - .env
